basePath: /
definitions:
  responses.BalanceResponse:
    properties:
      balance:
        example: 0
        type: number
    type: object
  responses.FeeResponse:
    properties:
      balance:
        example: 0
        type: number
    type: object
  responses.UTXO:
    properties:
      address:
        type: string
      amount:
        type: number
      confirmations:
        type: integer
      height:
        type: integer
      satoshis:
        type: integer
      scriptPubKey:
        type: string
      txid:
        type: string
      vout:
        type: integer
    type: object
  responses.UTXOResponse:
    properties:
      utxo:
        items:
          $ref: '#/definitions/responses.UTXO'
        type: array
    type: object
info:
  contact:
    email: nk
    name: API Support
  description: This is BUTTON Node API responseModels documentation
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Swagger BUTTON Node API
  version: "1.0"
paths:
  /bch/balance/{address}:
    get:
      description: return balance of account in BCH for specific node
      parameters:
      - description: address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.BalanceResponse'
            type: array
      summary: BCH balance of account
  /bch/transactionFee:
    get:
      description: return fee of tx in BCH
      parameters:
      - description: address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.FeeResponse'
            type: array
      summary: BCH fee of tx
  /bch/utxo/{address}:
    get:
      description: return UTXO of account
      parameters:
      - description: address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.UTXOResponse'
            type: array
      summary: BCH UTXO of account
swagger: "2.0"
