FROM golang:latest AS builder

RUN mkdir /build
ADD ltc /build
WORKDIR /build
RUN go get -d ./...
RUN go build -o bin/main .

FROM ubuntu:latest
COPY --from=builder /build/bin /app
EXPOSE 8080
CMD ["/app/main"]