FROM golang

RUN mkdir /app
ADD waves /app
WORKDIR /app

RUN go get github.com/gin-gonic/gin
RUN go get github.com/button-tech/utils-node-tool/waves/handlers
RUN go get github.com/gin-gonic/contrib/cors
RUN go get github.com/swaggo/gin-swagger
RUN go get github.com/swaggo/gin-swagger/swaggerFiles
RUN go get github.com/swaggo/swag
RUN go get github.com/imroc/req

RUN go build -o main .

CMD ["/app/main"]