FROM golang:latest AS builder

RUN mkdir /build
ADD btc /build
WORKDIR /build
RUN go get -d ./...
RUN go build -o main 

FROM ubuntu:latest
COPY --from=builder /build/main /app
EXPOSE 8080
CMD ["/app/main"]