FROM golang:latest AS builder

RUN mkdir /build
ADD waves /build
WORKDIR /build
RUN go get -d ./...
RUN go build -o bin/main .

FROM golang:latest
COPY --from=builder /build/bin /app
EXPOSE 8080
CMD ["/app/main"]