basePath: /
host: localhost:8080
info:
  contact:
    email: nk
    name: API Support
  description: This is BUTTON Node API responseModels documentation
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Swagger BUTTON Node API
  version: "1.0"
paths:
  /btc/balance/{address}:
    get:
      description: return balance of account in BTC for specific node
      parameters:
      - description: address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      summary: BTC balance of account
swagger: "2.0"
