basePath: /
definitions:
  responses.BalanceResponse:
    properties:
      balance:
        example: "0"
        type: string
    type: object
  responses.BalancesResponse:
    properties:
      balances:
        type: object
    type: object
  responses.TransactionFeeResponse:
    properties:
      fee:
        example: 0
        type: number
    type: object
  responses.UTXO:
    properties:
      address:
        type: string
      amount:
        type: number
      confirmations:
        type: integer
      height:
        type: integer
      satoshis:
        type: integer
      scriptPubKey:
        type: string
      txid:
        type: string
      vout:
        type: integer
    type: object
  responses.UTXOResponse:
    properties:
      utxo:
        items:
          $ref: '#/definitions/responses.UTXO'
        type: array
    type: object
info:
  contact:
    email: nk
    name: API Support
  description: This is BUTTON Node API responseModels documentation
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Swagger BUTTON Node API
  version: "1.0"
paths:
  /btc/balance/{address}:
    get:
      description: return balance of account in BTC for specific node
      parameters:
      - description: address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.BalanceResponse'
            type: array
      summary: BTC balance of account
  /btc/balances:
    post:
      description: return balances of accounts in BTC
      parameters:
      - description: addressesArray
        in: body
        name: addressesArray
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.BalancesResponse'
            type: array
      summary: BTC balance of accounts by list
  /btc/bestTransactionFee:
    get:
      description: return Amount of BTC that you need to send a transaction
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.TransactionFeeResponse'
            type: array
      summary: return Amount of BTC that you need to send a transaction
  /btc/transactionFee:
    get:
      description: return BTC fee
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.TransactionFeeResponse'
            type: array
      summary: BTC fee
  /btc/utxo/{address}:
    get:
      description: return UTXO of account
      parameters:
      - description: address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.UTXOResponse'
            type: array
      summary: BTC UTXO of account
swagger: "2.0"
