basePath: /
definitions:
  responses.BalanceResponse:
    properties:
      balance:
        type: string
    type: object
  responses.BalancesResponse:
    properties:
      balances:
        type: object
    type: object
  responses.GasPriceResponse:
    properties:
      gasPrice:
        example: 0
        type: integer
    type: object
  responses.TransactionFeeResponse:
    properties:
      fee:
        example: 0
        type: number
    type: object
info:
  contact:
    email: nk
    name: API Support
  description: This is BUTTON Node API responseModels documentation
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Swagger BUTTON Node API
  version: "1.0"
paths:
  /eth/balance/{address}:
    get:
      description: return balance of account in ETH for specific node
      parameters:
      - description: address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.BalanceResponse'
            type: array
      summary: ETH balance of account
  /eth/balances:
    post:
      description: return balances of accounts in ETH
      parameters:
      - description: addressesArray
        in: body
        name: addressesArray
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.BalancesResponse'
            type: array
      summary: ETH balance of accounts by list
  /eth/gasPrice:
    get:
      description: return Amount of ETH that you need to send a transaction
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.GasPriceResponse'
            type: array
      summary: return gas price of specific node
  /eth/tokenBalance/{sc-address}/{address}:
    get:
      description: return balance of specific token in ETH node
      parameters:
      - description: address
        in: path
        name: address
        required: true
        type: string
      - description: sc-address
        in: path
        name: sc-address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.BalanceResponse'
            type: array
      summary: return balance of specific token in ETH node
  /eth/tokenBalances:
    post:
      description: return tokens balances of account
      parameters:
      - description: addressesArray
        in: body
        name: addressesArray
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.BalancesResponse'
            type: array
      summary: ETH ERC-20 tokens balance of account by list of smart contracts
  /eth/transactionFee:
    get:
      description: return Amount of ETH that you need to send a transaction
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.TransactionFeeResponse'
            type: array
      summary: return Amount of ETH that you need to send a transaction
swagger: "2.0"
