basePath: /
definitions:
  responses.BalanceResponse:
    properties:
      balance:
        type: string
    type: object
info:
  contact:
    email: nk
    name: API Support
  description: This is BUTTON Node API responseModels documentation
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Swagger BUTTON Node API
  version: "1.0"
paths:
  /waves/balance/{address}:
    get:
      description: return balance of account in Waves for specific node
      parameters:
      - description: address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.BalanceResponse'
            type: array
      summary: Waves balance of account
swagger: "2.0"
